##**[5주차]과제**
- 아래의 과제1)의 코드를 완성하시오.
- 모든 코드의 결과를 출력하여, .ipynb의 링크를 **[5주차]/[5주차]과제**에 제출하시오.\
(실습 제출 예시: 5주차_2020XXXX_이름.ipynb 코드 링크)

In [531]:
print("신동엽", "2343035")

신동엽 2343035

In [532]:
from google.colab import auth

auth.authenticate_user()
!gcloud config get-value account

2343035@donga.ac.kr

In [533]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [534]:
#작업폴더 경로 참고 : data파일이 있는 폴더의 경로를 작성
workspace_path = '/content/drive/MyDrive/deepLearning'

# [과제 1] activation func, hyper-parameter, optimizer등을 변경하여 와인 품질(quality)를 예측하는 모델의 accuracy(정확도)를 0.5 이상의 성능을 달성하여라.

## 조건 :
1. epoch 수는 최대 20으로 제한
2. 모델의 레이어는 2개(입력층, 출력층)로 제한
3. 입력층의 노드수는 256개로 하고 input_shape은 xTrain.shape[1]과 동일한 값으로 설정할 것

    예시) layer추가
```python
# 입력층 예시
netwrok.add(tf.keras.layers.Dense(노드 수, activation_func='activation_func', input_shape=xTrain.shape[1], kernel_initializer=initializer))
# 출력층 예시
network.add(tf.keras.layers.Dense(노드 수, activation='activation_func', kernel_initializer=initializer))

##- 개선사항을 작성해 주세요 :

입력층 활성화 함수를 ReLU, 출력층 활성화 함수를 softmax로 설정
입력층과 출력층 차이에 dropout 수치를 0.4로 설정
optimizer는 adam, 손실함수는 sparse_categorical_corssentropy
epoch는 19회로 설정하여 정확도 0.515 달성함

In [535]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [536]:
red_df = pd.read_csv(os.path.join(workspace_path,'winequality-red.csv'), sep=';', header=0, engine='python')
red_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [537]:
white_df = pd.read_csv(os.path.join(workspace_path,'winequality-white.csv'), sep=';', header=0, engine='python')
white_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [538]:
wine =  pd.concat([red_df, white_df])

In [539]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         6497 non-null   float64
 1   volatile acidity      6497 non-null   float64
 2   citric acid           6497 non-null   float64
 3   residual sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free sulfur dioxide   6497 non-null   float64
 6   total sulfur dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 659.9 KB

In [540]:
sorted(wine.quality.unique())

[np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [541]:
wine.quality.value_counts()

quality
6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: count, dtype: int64

In [542]:
# 코드를 작성해 주세요
# 레이블링 인코딩 필요
# 힌트 : ?? = ??.apply(lambda x: x-3)
wine['quality'] = wine['quality'].apply(lambda x: x-3)

In [543]:
sorted(wine.quality.unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)]

In [544]:
# 코드를 작성해 주세요
# 힌트 : 와인의 품질을 예측하는 모델이므로 훈련 데이터셋도 품질에 훈련셋으로 준비되어야 함
# xTrain = ??.drop(???, axis=1)
# yTrain = ??

xTrain = wine.drop('quality', axis=1)
yTrain = wine['quality']

In [545]:
xTrain, xTest, yTrain, yTest = train_test_split(xTrain, yTrain, test_size=0.2)

In [546]:
# 실험 결과 재현을 위한 seed 고정
SEED = 4
os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_DETERMINISTIC_OPS'] = '1'
tf.random.set_seed(SEED)
initializer = tf.keras.initializers.GlorotUniform(seed=SEED)

In [547]:
def build_model():
  network = tf.keras.models.Sequential()

  network.add(tf.keras.layers.Dense(256,activation='relu', input_shape=(xTrain.shape[1],), kernel_initializer=initializer))
  network.add(tf.keras.layers.Dropout(0.4))
  network.add(tf.keras.layers.Dense(256,activation='softmax', kernel_initializer=initializer))



  network.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

  return network

In [548]:
model = build_model()

history = model.fit(xTrain, yTrain, epochs=19, batch_size=1, validation_split=0.25)

Epoch 1/19

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.3780 - loss: 2.4561 - val_accuracy: 0.4285 - val_loss: 1.4331
Epoch 2/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4265 - loss: 1.3346 - val_accuracy: 0.4177 - val_loss: 1.3579
Epoch 3/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4398 - loss: 1.3171 - val_accuracy: 0.4254 - val_loss: 1.3158
Epoch 4/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4416 - loss: 1.3038 - val_accuracy: 0.4169 - val_loss: 1.2909
Epoch 5/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4439 - loss: 1.2773 - val_accuracy: 0.4208 - val_loss: 1.2944
Epoch 6/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - accuracy: 0.4560 - loss: 1.2775 - val_accuracy: 0.4177 - val_loss: 1.2558
Epoch 7/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4401 - loss: 1.2711 - val_accuracy: 0.4208 - val_loss: 1.2574
Epoch 8/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4601 - loss: 1.2604 - val_accuracy: 0.4277 - val_loss: 1.2306
Epoch 9/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.4519 - loss: 1.2668 - val_accuracy: 0.4346 - val_loss: 1.2543
Epoch 10/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4647 - loss: 1.2459 - val_accuracy: 0.4238 - val_loss: 1.2197
Epoch 11/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4711 - loss: 1.2464 - val_accuracy: 0.4362 - val_loss: 1.2092
Epoch 12/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - accuracy: 0.4706 - loss: 1.2145 - val_accuracy: 0.4769 - val_loss: 1.2081
Epoch 13/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4650 - loss: 1.2148 - val_accuracy: 0.4400 - val_loss: 1.2128
Epoch 14/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 14s 3ms/step - accuracy: 0.4793 - loss: 1.2131 - val_accuracy: 0.4692 - val_loss: 1.2000
Epoch 15/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4698 - loss: 1.2065 - val_accuracy: 0.4792 - val_loss: 1.2002
Epoch 16/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4758 - loss: 1.2095 - val_accuracy: 0.4792 - val_loss: 1.1924
Epoch 17/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4583 - loss: 1.2069 - val_accuracy: 0.4715 - val_loss: 1.2144
Epoch 18/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step - accuracy: 0.4809 - loss: 1.1945 - val_accuracy: 0.4600 - val_loss: 1.1672
Epoch 19/19
3897/3897 ━━━━━━━━━━━━━━━━━━━━ 13s 3ms/step - accuracy: 0.4804 - loss: 1.1919 - val_accuracy: 0.4708 - val_loss: 1.1795

In [549]:
test_loss, test_acc = model.evaluate(xTest, yTest)

41/41 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5146 - loss: 1.1097

In [550]:
print('테스트 정확도 : ', round(test_acc,3))

테스트 정확도 :  0.515